tag: kitti
wandb_project_name: "outlier_network_kitti"

enable_timing: False
training_mode: True
supervised_training: True
train_outlier_model: True
train_correction_model: False
train_pose_outlier_model: True
load_outlier_model: True
load_correction_model: False
load_pose_outlier_model: False

batch_size:    10
multiframe_size: 13
similarity_threshold: 0.5
num_epochs:   10
lr_start:      0.0001
lr_decay:      0.1
threshold:     0.5
log_batch_period: 5
save_model_epoch_period: 5

pipeline_steps:
  - normalize-correspondences
  - point-net-outlier-detector
  - dlt-pose-solver
  - so3-matrix-projector
  - opencv-pose-solver
  - back-to-world-frame
  - pose-outlier-network


loss_weights:
  # last-sv-loss: 15.0
  # last-svs-ratio-loss: 10.0
  # reprojection-loss: 0.01
  # inlier-loss: 0.5

  last-sv-loss: 0
  last-svs-ratio-loss: 0
  reprojection-loss: 0
  inlier-loss: 0
  supervised-pose-loss: 1
  auxiliary-supervised-pose-loss: 1
  self-supervised-inlier-loss: 0.0
  self-supervised-inlier-normal-loss: 0.0
  self-supervised-pose-loss: 0.0

kalman_parameters_path: /srv/beegfs02/scratch/deep_slam/data/data_sets/kitti/kalman_parameters/
outlier_rejection_model_path: /srv/beegfs02/scratch/deep_slam/data/vukasin/semester_project/data/models_multiframe/sup/outlier_network_state_dict.pth
pose_outlier_model_path: /srv/beegfs02/scratch/deep_slam/data/vukasin/semester_project/data/models_multiframe/sup/pose_outlier_network_state_dict.pth
extracted_data_path: /srv/beegfs02/scratch/deep_slam/data/vukasin/semester_project/data/correspondences/extracted_features_multiframe_all_new_format_TMP.h5
write_path: /srv/beegfs02/scratch/deep_slam/data/vukasin/semester_project/data/models_multiframe/sup/

#train_sequences: ['00','01','02','03','04','05','06','07','08']
train_sequences: ['00']
test_sequences: ['00']
